server:
    port: 8085

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes:
                - id: billing
                uri: http://localhost:8081
                predicates:
                    - Path=/api/v1/billings
                - id: customer
                uri: http://localhost:8080
                predicates:
                    - Path= /api/v1/customers
                - id: fraud
                uri: http://localhost:8083
                predicates:
                    - Path= /api/v1/fraud-check/**

