server:
    port: 8081

spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

    application:
        name: billing

    datasource:
        username: 'postgres'
        url: jdbc:postgresql://localhost:5432/billing
        password: 'changeme'

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: 'true'
        hibernate:
            ddl-auto: update
        show-sql: 'true'

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
